### ISSUE TITLE
Help wanted to clean up the code

### ISSUE THREAD

**Issue by dermatologist** [dermatologist/fhirformjs#5]
Help wanted to clean up the code and to complete the remaining mapping. This may be great for those with an interest in health IT and FHIR. Any meaningful contribution will be appreciated and accepted.

**Comment by joekendal** [comment]
@dermatologist what mapping(s) are missing?

**Comment by dermatologist** [comment]
Hi @joekendal Thanks to @mfferreira, most of the common ones are completed, I believe. We still do not have support for ValueSets (example:  https://www.hl7.org/fhir/questionnaire-example-gcs.json.html )
